### ISSUE TITLE
Animations not working in Firefox 34.0.5

### ISSUE THREAD

**Issue by dceballos** [jQueryKeyframes/jQuery.Keyframes#30]
Hi, animations do not seem to be working on Firefox.  They are working fine in Chrome and Safari, but never seem to start in Firefox.  

I'm defining my animation like this:

``` javascript
     $.keyframe.define([{
      name: 'marquee',
        '0%': {'left': '100%'},
        '100%': {'left': endOffset+'px'}
    }]);
```

And starting it like this:

``` javascript
    $('#ticker').playKeyframe({
        name: 'marquee',
        duration: duration,
        timingFunction: 'linear',
        fillMode: 'backwards',
        iterationCount: 'infinite',
      },function() {
        $('#ticker').pauseKeyframe();
        refresh();
      }   
    ); 
```

Thank you

**Comment by Kum0ri** [comment]
Hi there,

Was with this exact same problem and i'm really glad u found the solution :) Just one thing, mabey you should change the documentation because when i made my setup i just followed the git documentation and in there u have :+1: 

$(selector).playKeyframe({
    name: 'trapdoor-sequence', // name of the keyframe you want to bind to the selected element
    duration: '1s', // [optional, default: 0, in ms] how long you want it to last in milliseconds
    timingFunction: 'linear', // [optional, default: ease] specifies the speed curve of the animation
    delay: 0, //[optional, default: 0]  how long you want to wait before the animation starts
    iterationCount: 'infinite', //[optional, default:1]  how many times you want the animation to repeat
    direction: 'normal', //[optional, default: 'normal']  which direction you want the frames to flow
    fillMode: 'forwards', //[optional, default: 'forward']  how to apply the styles outside the animation time, default value is forwards
    complete: function(){} //[optional] Function fired after the animation is complete. If repeat is infinite, the function will be fired every time the animation is restarted.
});

The delay number is still delay : 0 and i guess everyone will follow in this problem. 

Great plugin tkx :)
