### ISSUE TITLE
Minor documentation error with playKeyframe

### ISSUE THREAD

**Issue by RobeeeJay** [jQueryKeyframes/jQuery.Keyframes#34]
Hi, thanks for your library, it was just what I needed to solve jerky animation without having to write keyframe code myself. :)

Discovered a small but significant error in the docs regarding the usage of playKeyframe with options passed as an object. It states you can pass a complete property, but you can't, it has to be passed as a second argument along with the object.

Noticed whilst using this in Angular and not having my callbacks firing. :)

**Comment by krazyjakee** [comment]
Wow! Not sure how I missed that. Will fix ASAP!

**Comment by krazyjakee** [comment]
Ok, i've submitted a fix, please check it out.

**Comment by RobeeeJay** [comment]
Works great now, just as documented, thank you!
