### ISSUE TITLE
animations broken

### ISSUE THREAD

**Issue by dceballos** [jQueryKeyframes/jQuery.Keyframes#36]
Things seem to be broken with the api changes introduced 6 days ago.  I can't quite tell what the problem is since I get no console errors but the examples are not working and I suspect that playKeyframe is broken again due to the api change.

**Comment by krazyjakee** [comment]
Which browser are the examples not working in?

**Comment by dceballos** [comment]
Chrome.  Also, the playKeyframe api keeps changing and every time I upgrade it breaks without a message.  It'd be nice if we got a console error when using invalid parameters :)

**Comment by krazyjakee** [comment]
I can't recreate this issue, are you able to post an example of your code?
