### ISSUE TITLE
Receive error when defining a keyframe: Uncaught ReferenceError: PrefixFree is not defined

### ISSUE THREAD

**Issue by atteeela** [jQueryKeyframes/jQuery.Keyframes#37]
Uncaught ReferenceError: PrefixFree is not defined jquery.keyframes.js?body=1:57    

       generate: function(frameData) {
            var frameName = frameData.name || "";
            var css = "@" + vendorPrefix + "keyframes " + frameName + " {";

            for (var key in frameData) {
                if (key !== "name" && key !== "media" && key !== "complete") {
                    css += key + " {";

                    for (var property in frameData[key]) {
                        css += property + ":" + frameData[key][property] + ";";
                    }

                    css += "}";
                }
            }

            css = PrefixFree.prefixCSS(css + "}");

            if(frameData.media){
                css = "@media " + frameData.media + "{" + css + "}";
            }

PrefixFree is not defined.

-- Just noticed comment on homepage that PrefixFree is required -- ... Please disregard

**Comment by ProWebSpecialist** [comment]
I face the same issue. Is there any solution?
