### ISSUE TITLE
Problem in IE and mobile browsers

### ISSUE THREAD

**Issue by carasik** [jQueryKeyframes/jQuery.Keyframes#38]
Hi, I'm using your plugin and this is great solution for my projects, but few days ago I started to learn svg animations and needed to change keyframes dynamically and I found one problem: all animations works properly in all browsers accept IE including 11 version and mobile browsers like Safari and Chrome on IOS 8. Here is my project on codepen http://codepen.io/carasik/pen/JozpBd and on my website http://repack.hol.es/codepen/ .I will be very grateful if you can help me with this

**Comment by krazyjakee** [comment]
I need a **minimal** example and a description of what is going wrong here. Please create a small single animation that doesn't work in IE11.

**Comment by carasik** [comment]
Sorry, here is new example http://codepen.io/carasik/pen/wBZerE . In this example animation works in all browsers accept IE11, Safari and Chrome on IOS 8. In these browsers element is standing at the same point instead of moving.
