### ISSUE TITLE
Delete custom keyframe

### ISSUE THREAD

**Issue by joeywisse** [jQueryKeyframes/jQuery.Keyframes#43]
Is it possible to delete custom keyframe? 

Something like:

<code>
$.keyframe.delete([{
            name: 'spin'
}]);
</code>

**Comment by krazyjakee** [comment]
You can achieve that with `$('style#spin').remove();`

**Comment by joeywisse** [comment]
That did the trick.

Thanks heaps!

**Comment by krazyjakee** [comment]
No probs!
